import colors

# Segments colors.
USERATHOST_BG = colors.BLUEISH
USERATHOST_FG = colors.WHITE

SSH_BG = colors.LIGHT_ORANGE
SSH_FG = colors.WHITE

CURRENTDIR_BG = colors.DARK_GREY
CURRENTDIR_FG = colors.LIGHT_GREY

READONLY_BG = colors.LIGHT_GREY
READONLY_FG = colors.RED

EXITCODE_BG = colors.RED
EXITCODE_FG = colors.WHITE

PADDING_BG = colors.BLACKISH

GIT_UNTRACKED_FILES_BG = colors.DARKER_GREY
GIT_UNTRACKED_FILES_FG = colors.PINKISH_RED
GIT_CHANGES_NOT_STAGED_BG = colors.DARKER_GREY
GIT_CHANGES_NOT_STAGED_FG = colors.LIGHTER_GOLD
GIT_ALL_CHANGES_STAGED_BG = colors.DARKER_GREY
GIT_ALL_CHANGES_STAGED_FG = colors.MID_GREEN
GIT_CLEAN_BG = colors.DARKER_GREY
GIT_CLEAN_FG = colors.LIGHT_GREY
GIT_CONFLICT_BG = colors.PINKISH_RED
GIT_CONFLICT_FG = colors.BLACKISH

VENV_BG = colors.SMERALD
VENV_FG = colors.EXTRA_LIGHT_GREY

JOBS_BG = colors.DARK_PURPLE
JOBS_FG = colors.WHITE

TIME_BG = colors.DARKER_GREY
TIME_FG = colors.MID_DARK_GREY
